import sys
import os

sys.path.append("/home/carl/dev/test.programs/Huggingface.tests/FineTuningIntentsAndSlots/")

from SaveFile import SaveFile
from Replace import Replace


def saveToFile(training_phrases, filename):

    with open(filename, "w") as f:
        f.write("# Generated by TrainingDataGenerator.py\n")
        f.write("# Number of examples: " + str(len(training_phrases)) + "\n")

        f.write("from Common.Constants import *\n")
        f.write("trainingData = [\n")

        for phrase in training_phrases:
            f.write("\t{\n")
            f.write("\t\t\"text\": '{}',\n".format(phrase["text"]))
            f.write('\t\t"intent": {},\n'.format(phrase["intent"]))
            f.write('\t\t"slots": {},\n'.format(phrase["slots"]))
            f.write("\t},\n")

        f.write("]")


if __name__ == "__main__":

    training_classes = [SaveFile, Replace]  # Class names. These classes must inherit from ITrainingDataGenerator
    training_phrases = []

    for training_class in training_classes:
        print("Generating training data for: " + training_class.__name__)
        for i in range(300):
            training_object = training_class()
            output = training_object()
            training_phrases.append(output)

    current_path = os.path.dirname(os.path.abspath(__file__))
    data_path = os.path.join(current_path, "../Training/")

    print("Saving training data to: " + data_path)
    saveToFile(training_phrases, os.path.join(data_path, "TrainerData.py"))
